//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public short Age { get; set; }
        public bool IsMan { get; set; }
        public System.DateTime BirthDate { get; set; }
        public double Salary { get; set; }
    
        public virtual Status Status { get; set; }
    }
}
